### ISSUE TITLE
We need a plugin for implementing multilingual fields for CKAN

### ISSUE THREAD

**Issue by riccardoerra** [smallmedia/iod-ckan#21]
Something like: https://github.com/ckan/ckanext-fluent?

I created multiple fields, some of them are per language, because we want to show for example different title and description based on the language of the website.

https://github.com/smallmedia/iod-ckan/blob/iod-v2.6/ckanext-iod_theme/ckanext/iod_theme/iod_dataset.json

So for example `title_en` will show only for user navigating the website in English.

How to achieve that and will this create issues? For example I noticed that the dataset `test` in http://iod-ckan-live.aws.smallmedia.org.uk/organization/iranopendata has no description even if the related fields are not empty.

![screen shot 2017-08-14 at 7 33 32 pm](https://user-images.githubusercontent.com/3142540/29285779-99851bc0-8127-11e7-8f24-d6db6bef50cc.png)

**Comment by riccardoerra** [comment]
Support:

> Regarding double entries for Title and Description:
> 
> You can create and display multilingual fields (EN users see the EN version of the content of title, FA users see the FA version) using the the plugin ckanext-fluent (https://github.com/ckan/ckanext-fluent), which integrates with ckanext-scheming. The README explains how to update your scheming schema. You'll need to add the fluent presets to your scheming presets.
> 
> Note that if you're going to make one of CKAN's core fields multilingual, like title, you'll need to follow the directions here (https://github.com/ckan/ckanext-fluent#fluent_core_translated-fields) rather than just applying the fluent_text preset to the field. The plugin includes snippets for displaying only one of the languages (i.e., visitors to the EN site only see the EN version of title, etc.) as well as snippets for displaying one entry field for each language in the forms (as seen in the README). You can customize those snippets if you want users to only see the fields for a single language when filling out forms.
> 
> https://github.com/ckan/ckanext-fluent

**Comment by riccardoerra** [comment]
Do I need to include `"form_languages": ["en", "fa_IR"],` in my dataset schema?

Because if I do I get this error when I try to save a dataset:
```
Error - <type 'exceptions.KeyError'>: 0
URL: http://192.168.33.10:5000/dataset/new
File '/home/vagrant/local/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/home/vagrant/local/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/home/vagrant/local/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/home/vagrant/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/vagrant/ckan/config/middleware/pylons_app.py', line 245 in inner
  result = application(environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/vagrant/ckan/lib/base.py', line 292 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/home/vagrant/local/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/vagrant/ckan/controllers/package.py', line 510 in new
  return self._save_new(context, package_type=package_type)
File '/vagrant/ckan/controllers/package.py', line 914 in _save_new
  pkg_dict = get_action('package_create')(context, data_dict)
File '/vagrant/ckan/logic/__init__.py', line 431 in wrapped
  result = _action(context, data_dict, **kw)
File '/vagrant/ckan/logic/action/create.py', line 166 in package_create
  package_plugin, context, data_dict, schema, 'package_create')
File '/vagrant/ckan/lib/plugins.py', line 239 in plugin_validate
  result = plugin.validate(context, data_dict, schema, action)
File '/vagrant/ckanext-scheming/ckanext/scheming/plugins.py', line 254 in validate
  return navl_validate(data_dict, schema, context)
File '/vagrant/ckan/lib/navl/dictization_functions.py', line 307 in validate
  if isinstance(value[0], dict):
KeyError: 0


CGI Variables
-------------
  AUTH_TYPE: 'cookie'
  CKAN_CURRENT_URL: '/dataset/new'
  CKAN_LANG: 'en'
  CONTENT_TYPE: 'application/x-www-form-urlencoded; charset=utf-8'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_ACCEPT_LANGUAGE: 'en-gb'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: 'ckan=ab07ffda541ef322e38e89c9af09ecef581c74908ab899d7bf27410f9742c3d486913f8f; csrftoken=5RB8ZFdsl8u3fvpsECTJVFNcZ4WTMFyt; sessionid=19hw9q89mac3q5c9lzrnzkfty4u3xdfe; _ga=GA1.1.204087434.1492535055; djdt=hide; AMCV_518ABC7455E462B97F000101%40AdobeOrg=1099438348%7CMCIDTS%7C17394%7CvVersion%7C2.1.0; _cb=D8ofmmCeomtQT_G-P; _cb_ls=1; _ceg.s=ouq86u; _ceg.u=ouq86u; _chartbeat2=.1502800374784.1502800374784.1.CKcCF2GXckpDEtgReCO6WI8BeoiyC; auth_tkt="8fb7b8c5355942e639ea6987a2537d7f5989dd65riccardo!userid_type=unicode"; __utma=86847064.204087434.1492535055.1498748947.1498748947.1; __utmz=86847064.1498748947.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
  HTTP_HOST: '192.168.33.10:5000'
  HTTP_ORIGIN: 'http://192.168.33.10:5000'
  HTTP_REFERER: 'http://192.168.33.10:5000/en/dataset/new'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8'
  PATH_INFO: '/dataset/new'
  REMOTE_ADDR: '192.168.33.1'
  REMOTE_USER: u'riccardo'
  REMOTE_USER_DATA: 'userid_type=unicode'
  REMOTE_USER_TOKENS: ['']
  REQUEST_METHOD: 'POST'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '5000'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <fanstatic.publisher.Delegator object at 0x7f7fa09c2590>
  beaker.cache: <beaker.cache.CacheManager object at 0x7f7fa09c2750>
  beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7f7fa09c2e50>>
  beaker.session: {'_accessed_time': 1504027563.48151, '_creation_time': 1504025875.424332}
  ckan.app: 'pylons_app'
  fanstatic.needed: <fanstatic.core.NeededResources object at 0x7f7f7ee2d4d0>
  paste.cookies: (<SimpleCookie: AMCV_518ABC7455E462B97F000101%40AdobeOrg='1099438348%7CMCIDTS%7C17394%7CvVersion%7C2.1.0' __utma='86847064.204087434.1492535055.1498748947.1498748947.1' __utmz='86847064.1498748947.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' _cb='D8ofmmCeomtQT_G-P' _cb_ls='1' _ceg.s='ouq86u' _ceg.u='ouq86u' _chartbeat2='.1502800374784.1502800374784.1.CKcCF2GXckpDEtgReCO6WI8BeoiyC' _ga='GA1.1.204087434.1492535055' auth_tkt='8fb7b8c5355942e639ea6987a2537d7f5989dd65riccardo!userid_type=unicode' ckan='ab07ffda541ef322e38e89c9af09ecef581c74908ab899d7bf27410f9742c3d486913f8f' csrftoken='5RB8ZFdsl8u3fvpsECTJVFNcZ4WTMFyt' djdt='hide' sessionid='19hw9q89mac3q5c9lzrnzkfty4u3xdfe'>, 'ckan=ab07ffda541ef322e38e89c9af09ecef581c74908ab899d7bf27410f9742c3d486913f8f; csrftoken=5RB8ZFdsl8u3fvpsECTJVFNcZ4WTMFyt; sessionid=19hw9q89mac3q5c9lzrnzkfty4u3xdfe; _ga=GA1.1.204087434.1492535055; djdt=hide; AMCV_518ABC7455E462B97F000101%40AdobeOrg=1099438348%7CMCIDTS%7C17394%7CvVersion%7C...)|utmcmd=(none)')
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x7f7fa9e918d0>
  paste.registry: <paste.registry.Registry object at 0x7f7f9c00d3d0>
  paste.throw_errors: True
  pylons.action_method: <bound method PackageController.new of <ckan.controllers.package.PackageController object at 0x7f7f7ef49690>>
  pylons.controller: <ckan.controllers.package.PackageController object at 0x7f7f7ef49690>
  pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
  pylons.pylons: <pylons.util.PylonsContext object at 0x7f7f7efa0a50>
  pylons.routes_dict: {'action': u'new', 'controller': u'package'}
  repoze.who.api: <repoze.who.api.API object at 0x7f7f7ee2db10>
  repoze.who.identity: <repoze.who identity (hidden, dict-like) at 140185565656304>
  repoze.who.logger: <logging.Logger object at 0x7f7fa0841e50>
  repoze.who.plugins: {'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f7fa09c2350>, 'friendlyform': <FriendlyFormPlugin 140186130586256>, 'auth_tkt': <CkanAuthTktCookiePlugin 140186130586192>}
  routes.route: <routes.route.Route object at 0x7f7fa087f050>
  routes.url: <routes.util.URLGenerator object at 0x7f7f7efa0850>
  webob._parsed_post_vars: (MultiDict([('_ckan_phase', 'dataset_new_1'), ('pkg_name', ''), ('title', ''), ('title_translated-en', ''), ('title_translated-fa_IR', ''), ('name', ''), ('notes_translated-en', ''), ('notes_translated-fa_IR', ''), ('theme_string', ''), ('tags_string', ''), ('owner_org', '52db8595-a40c-4d04-bdeb-eb444545229f'), ('private', 'True'), ('date_start_gregorian', ''), ('date_end_gregorian', ''), ('date_start_iranian', ''), ('date_end_iranian', ''), ('publisher', ''), ('publisher_url', ''), ('geographic_string', ''), ('methodology', 'Dataset extracted from a PDF table with Tabula.'), ('license_id', 'notspecified'), ('save', '')]), <FakeCGIBody at 0x7f7f7efa0110 viewing MultiDict([('_c...'')])>)
  webob._parsed_query_vars: (GET([]), '')
  webob.adhoc_attrs: {'errors': 'ignore', 'response': <Response at 0x7f7f7ee2d450 200 OK>, 'language': 'en-us'}
  webob.is_body_readable: True
  webob.is_body_seekable: False
  wsgi process: 'Multithreaded'
  wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7f7f7efa0850>, {'action': u'new', 'controller': u'package'})
------------------------------------------------------------

            <p>Additionally an error occurred while sending the &lt;weberror.reporter.EmailReporter object at 0x7f7f7edcf850&gt; report:

            <pre>Traceback (most recent call last):
  File "/home/vagrant/local/lib/python2.7/site-packages/weberror/errormiddleware.py", line 471, in send_report
    rep.report(exc_data)
  File "/home/vagrant/local/lib/python2.7/site-packages/weberror/reporter.py", line 47, in report
    server = smtplib.SMTP(self.smtp_server)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
</pre>
            </p>2017-08-29 17:26:03,720 INFO  [ckan.lib.base]  /dataset/new render time 0.097 seconds
2017-08-29 17:26:03,777 INFO  [ckan.lib.base]  /api/i18n/en render time 0.002 seconds
```

**Comment by kmbn** [comment]
You do need to include `"form_languages": ["en", "fa_IR"],` in iod_theme dataset schema. If you don't, the content of the fields won't change when you switch languages.

The error arises because ckanext-fluent doesn't expect a language code as exotic as `fa_IR`, even though that language code is used by CKAN itself. ckanext-fluent checks if the language codes associated with submitted form fields are ISO 639 codes and throws an error if they aren't.

To see what's causing the problem, have a look at `ckanext-fluent/ckanext/fluent/validators.py`: line 10 defines the regex used to determine if a language code is ISO 639, and the checks occur on lines 109, 141, 239 and 283. The check on line 141 seems to be the one that causes the error in this case, but they'd all pose a problem eventually.

To work around this, you can either change the regex on line 10 so that codes like `fa_IR`, `zh_CN`, etc. are also matched, or you can just change the if statements on lines 109, etc. to `if not m and lang != 'fa_IR':`. 

For a quick fix, I just changed the if statements. I was then able to submit the form with EN and FA titles and descriptions without getting an error, and when I switched languages afterwards, the contents of the fields changed accordingly.

If you're going to opt for changing the regex, it would be a good pull request for ckanext-fluent. Let me know if you're going to work on it, otherwise, I'll take a crack at it.

**Comment by riccardoerra** [comment]
Thanks for the help!

I change the regex to this:
https://github.com/smallmedia/iod-ckan/blob/cd176c2c93e81b239c85796ce2cb60e8228d522d/ckanext-iod_theme/ckanext/iod_theme/validators.py#L10

If you think that's good enough I can open a PR in ckanext-fluent.

**Comment by riccardoerra** [comment]
https://github.com/smallmedia/ckanext-fluent/blob/1a0b976957ed7d01d57271a21a3b97643256a5b6/ckanext/fluent/validators.py#L10
